# Generated by Django 5.0.6 on 2024-08-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField()),
                ('uphone', models.IntegerField()),
                ('uemail', models.TextField()),
                ('uaddress', models.TextField()),
                ('upassword', models.TextField()),
                ('ucnfpassword', models.TextField()),
            ],
        ),
    ]
