# Generated by Django 5.0.6 on 2024-08-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ucnfpassword',
        ),
    ]
