# Generated by Django 5.0.6 on 2024-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_advocate_langauges_practice_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice_areas',
            name='admiralty_and_maritime_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='aname',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='bankruptcy_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='civil_right_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='corporate_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='criminal_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='employment_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='entertainment_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='environmental_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='estate_planing_and_probate_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='family_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='healthcare_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='immigration_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='intelectual_property_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='personal_injury_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='real_estate_law',
        ),
        migrations.RemoveField(
            model_name='practice_areas',
            name='tax_law',
        ),
        migrations.AddField(
            model_name='advocate',
            name='off_day',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='practice_areas',
            name='p_areas',
            field=models.ManyToManyField(to='app.advocate'),
        ),
    ]
