# Generated by Django 5.0.6 on 2024-08-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_practice_areas_p_areas_practice_areas_p_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langauges',
            name='aname',
        ),
        migrations.RemoveField(
            model_name='langauges',
            name='english',
        ),
        migrations.RemoveField(
            model_name='langauges',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='langauges',
            name='malayalam',
        ),
        migrations.AddField(
            model_name='langauges',
            name='languages',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Selected_lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.langauges')),
                ('aname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advocate')),
            ],
        ),
    ]
