# Generated by Django 5.0.6 on 2024-08-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_languages_langauges_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenumber', models.IntegerField()),
                ('court', models.TextField()),
                ('judge', models.TextField()),
                ('reg_date', models.DateField()),
                ('next_hearing', models.DateField()),
                ('case_summery', models.TextField()),
                ('case_subjet', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('aname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.TextField()),
                ('aname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advocate')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.TextField()),
                ('daddress', models.TextField()),
                ('dphno', models.TextField(null=True)),
                ('demail', models.TextField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cases')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
