# Generated by Django 5.0.6 on 2024-10-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_advocate_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
