# Generated by Django 5.0.6 on 2024-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chat_read_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='read_status',
            new_name='advread_status',
        ),
        migrations.AddField(
            model_name='chat',
            name='userread_status',
            field=models.BooleanField(default=False),
        ),
    ]
