# Generated by Django 5.0.6 on 2024-11-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_chat_advs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_status',
            field=models.BooleanField(default=False),
        ),
    ]
