# Generated by Django 5.0.6 on 2024-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cases_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.TextField(null=True)),
            ],
        ),
    ]
