# Generated by Django 5.0.6 on 2024-11-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_case_types_court_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='casetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.case_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cases',
            name='courttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.court_type'),
            preserve_default=False,
        ),
    ]
