# Generated by Django 5.0.6 on 2024-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cases_casetype_cases_courttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_types',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='court_type',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
