# Generated by Django 5.0.6 on 2024-11-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_case_types_status_court_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='uname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
    ]
