# Generated by Django 5.0.6 on 2024-12-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cases_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='case_subjet',
            new_name='case_subject',
        ),
    ]
