# Generated by Django 5.0.6 on 2024-12-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_case_subjet_cases_case_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='casenumber',
            field=models.TextField(),
        ),
    ]
