# Generated by Django 5.0.6 on 2024-12-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_cases_casenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='case_status',
        ),
    ]
